binary_sensor:
  - id: !extend grid_active
    address: 4553
    bitmask: 0x200
  - id: !extend on_battery
    address: 4553
    bitmask: 0x100
text_sensor:    
  - id: !extend charger_status
    lambda: |-
      uint16_t sensorIndex = swapBytes(modbus_controller::word_from_hex_str(x, 0));
      switch (sensorIndex) {
        case 10: return std::string("Off");
        case 11: return std::string("Idle");
        case 13: return std::string("Charging");
        default: return std::string(x);
      }
select:
  - id: !extend max_total_charge_current
    optionsmap:
      "10": 10
      "20": 20
      "30": 30
      "40": 40
      "50": 50
      "60": 60
      "70": 70
      "80": 80
      "90": 90
      "100": 100
      "110": 110
      "120": 120
      "130": 130
      "140": 140
  - id: !extend utility_charge_current
    optionsmap:
      "10": 10
      "20": 20
      "30": 30
      "40": 40
      "50": 50
      "60": 60
      "70": 70
      "80": 80
      "90": 90
      "100": 100
