substitutions:
  device_name: "powmr-inverter"
  node_name: "PowMr Inverter"
  node_id: powmr_inverter
  inverter_tx_pin: GPIO16
  inverter_rx_pin: GPIO17
  inverter_voltage_offset: "0"
  pzem_tx_pin: GPIO1
  pzem_rx_pin: GPIO3
  pzem_voltage_offset: "1"
  pzem_current_offset: "0.04"
  update_interval: 30s # Minimum 10s recommended to avoid duplicate command errors
  select_skip_updates: "2"
  pzem_update_interval: 6s # Needs to be 1/5 of update interval because of smoothing filter on pzem readings

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

packages:
  main: !include powmr-inverter/main.yaml
  # You can replace next 2 lines with your common configs for all devices
  common_system: !include powmr-inverter/includes/common_system.yaml
  common_sensors: !include powmr-inverter/includes/common_sensors.yaml

logger:
  level: WARN
  baud_rate: 0
  logs:
    component: ERROR # Fix for issue #4717 "Component xxxxxx took a long time for an operation"

time:
  - platform: homeassistant
    id: hass_time
