esphome:
  name: "${device_name}"
  friendly_name: "${node_name}"
  comment: "Monitor and control a PowMr inverter"
  includes:
    - "${device_name}/helpers"
  project:
    name: "odya.esphome-powmr-hybrid-inverter"
    version: 1.3.3

packages:
  inverter: !include modules/inverter.yaml

#  for using PZEM uncomment this line:  
#  pzem: !include modules/pzem.yaml

#  for debug uncomment this line:
#  debug: !include modules/debug.yaml

#  changes for model POW-HVM4.2M-24V:
#  pow-hvm4.2m-24v: !include modules/pow-hvm4.2m-24v.yaml
#  changes for model POW-HVM10.2M-48V:
#  pow-hvm10.2m-48v: !include modules/pow-hvm10.2m-48v.yaml

#  voltage config write registers, 24V battery
  voltage-registers: !include modules/voltage-registers.yaml
# 48V battery, uncomment this lines:
#number:
#  - id: !extend back_to_utility_source_voltage
#    min_value: 45
#    max_value: 51
#    step: 1
#  - id: !extend back_to_battery_source_voltage
#    min_value: 48
#    max_value: 58
#    step: 1
#  - id: !extend bulk_charging_voltage
#    min_value: 48
#    max_value: 61
#  - id: !extend floating_charging_voltage
#    min_value: 48
#    max_value: 61
